/**
 * Custom ProseMirror schema for QuillMark documents.
 * Extends the default prosemirror-markdown schema with:
 * - Underline mark for <u>text</u> syntax
 */

import { Schema, type NodeSpec, type MarkSpec, type Node } from 'prosemirror-model';
import { schema as markdownSchema } from 'prosemirror-markdown';
import { tableNodes } from 'prosemirror-tables';

/**
 * Escape HTML entities to prevent XSS when inserting content into DOM attributes.
 */
function escapeHtml(text: string): string {
	const div = document.createElement('div');
	div.textContent = text;
	return div.innerHTML;
}

/**
 * Table node specs generated by prosemirror-tables.
 * Produces: table, table_row, table_cell, table_header
 */
const tableNodeSpecs = tableNodes({
	tableGroup: 'block',
	cellContent: 'block+',
	cellAttributes: {}
});

/**
 * Custom nodes extending the markdown schema
 */
const customNodes = {
	...markdownSchema.spec.nodes.toObject(),
	...tableNodeSpecs,

	/**
	 * Inline metadata block - represents YAML metadata blocks that appear
	 * after the main frontmatter (e.g., for indorsements).
	 * These are hidden in the rich text view but preserved in the document.
	 */
	inline_metadata: {
		group: 'block',
		atom: true,
		attrs: {
			content: { default: '' }
		},
		toDOM(node: Node) {
			const content = node.attrs.content as string;
			const escaped = escapeHtml(content);
			return [
				'div',
				{
					class: 'pm-inline-metadata',
					'data-metadata': escaped,
					style: 'display: none',
					title: 'Inline metadata block (hidden)'
				},
				`---\n${escaped}\n---`
			] as const;
		},
		parseDOM: [
			{
				tag: 'div.pm-inline-metadata',
				getAttrs(dom: HTMLElement) {
					return { content: dom.getAttribute('data-metadata') || '' };
				}
			}
		]
	} satisfies NodeSpec
};

/**
 * Custom marks extending the markdown schema
 */
const customMarks = {
	...markdownSchema.spec.marks.toObject(),

	/**
	 * Underline mark - represents <u>text</u> syntax
	 */
	underline: {
		parseDOM: [{ tag: 'u' }, { style: 'text-decoration=underline' }],
		toDOM() {
			return ['u', 0] as const;
		}
	} satisfies MarkSpec,

	/**
	 * Strikethrough mark - represents ~~text~~ syntax
	 */
	strikethrough: {
		parseDOM: [
			{ tag: 's' },
			{ tag: 'strike' },
			{ tag: 'del' },
			{ style: 'text-decoration=line-through' }
		],
		toDOM() {
			return ['s', 0] as const;
		}
	} satisfies MarkSpec
};

/**
 * The QuillMark schema - extends prosemirror-markdown with custom nodes/marks
 */
export const quillmarkSchema = new Schema({
	nodes: customNodes,
	marks: customMarks
});

/**
 * Re-export base markdown schema for reference
 */
export { markdownSchema };
